### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by eliocamp** [moodymudskipper/unglue#6]
The default behaviour when there's duplicated variable names is to append `.n` to the result. 

``` r
string <- "the unglue package is such a wonderful package"
pattern <- "the {name} {object} is such a {adjective} {object}"
unglue::unglue(string, pattern)
#> $`1`
#>     name  object adjective object.1
#> 1 unglue package wonderful  package
```

It would be very nice to have the option to just drop them (and issue a warning/error if the first `object` does not equal the second one. I know I could probably work around the issue by putting a dummy variable, but in my use case I want to have a single "master pattern" that both glues and unglues. Specifically, my pattern is a folder + filename structure in which some variables appear both as a folder as and as a filename.

**Comment by moodymudskipper** [comment]
I understand your issue but 2 things make it hard for me to make it work as you suggest :

* `unglue` functions can be fed several patterns, and would use the first that works, so I can't make a pattern trigger an error or warning if the next one might have worked fine
* going both ways with a single pattern doesn't work all the time (in your example if name and object include spaces `unglue` wouldn't return it back as the original unless you'd use appropriate regex), so your use case might not be general enough to have a dedicated feature

-----------------

HOWEVER

I see value in requiring in the pattern that `object` matches twice the same value if used twice, what about having : 

```
string <- "the unglue package is such a wonderful package"
pattern <- "the {name} {object} is such a {adjective} {object}"
unglue::unglue(string, pattern)
#> $`1`
#>     name  object adjective
#> 1 unglue package wonderful
```

and 

```
string <- "the unglue package is such a wonderful idea" # last word was changed
pattern <- "the {name} {object} is such a {adjective} {object}"
unglue::unglue(string, pattern)
#>  Named list() # current behavior when not matched
```

using regex in the 2nd `{object}` instance would trigger an error, and in your case you'd do your own check to see if there was a match or not to trigger errors when relevant, and you'd be able to keep a single pattern for _glue_ and _unglue_.

----------------------

ALTERNATE OPTION

give a `duplicate` argument to _unglue_ functions, which should be a function of 2 (or n, or dots) arguments or formula lambda, and you'd have : 

```
string <- "the unglue package is such a wonderful package"
pattern <- "the {name} {object} is such a {adjective} {object}"
unglue::unglue(string, pattern, duplicate = ~.x) # taking the first
#> $`1`
#>     name  object adjective
#> 1 unglue package wonderful
```

and here you're free to trigger an error if it's appropriate for your use case :

```
 string <- "the unglue package is such a wonderful package"
pattern <- "the {name} {object} is such a {adjective} {object}"
unglue::unglue(string, pattern, duplicate = ~if(.x != .y) stop("inconsistent object value") else .x)
#> $`1`
#>     name  object adjective
#> 1 unglue package wonderful
```

to illustrate further : 

```
 string <- "the unglue package is such a wonderful idea"
pattern <- "the {name} {object} is such a {adjective} {object}"
unglue::unglue(string, pattern, duplicate = paste0)
#> $`1`
#>     name     object adjective
#> 1 unglue packageidea wonderful
```

A value `duplicate = NA`, probably the default, would not apply a function but check if `duplicate `instances matched the same string and match only if they did.

--------------

I think I like the last idea but I will need to let it rest and get back to it with a fresh mind

**Comment by moodymudskipper** [comment]
Just noticed that the following works already, not entirely relevant as the pattern differs from the one you'd use with *glue*, but quite neat too and might deserve an example in the doc : 

``` r
string <- c("the unglue package is such a wonderful package",
            "the unglue package is such a wonderful idea")
pattern <- "the {name} {object} is such a {adjective} {=\\2}"
unglue::unglue(string, pattern)
#> $`1`
#>     name  object adjective
#> 1 unglue package wonderful
#> 
#> $`2`
#>   name object adjective
#> 2 <NA>   <NA>      <NA>
```

<sup>Created on 2019-08-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by moodymudskipper** [comment]
* `multiple` might be a better name than `duplicate`
* try to make it work with `multiple = list` too (`unglue_data` should create a list column in that case)
* we should decide if current behaviour should still be available and if so would it be by default and what would be the argument value in that case. Right now I think we can just drop it
* decide between `multiple = NULL` and `multiple = NA` for consistency, `TRUE` and `FALSE` are also options if we find a fitting argument name.
* this `multiple = NA` option (or other above) would simply translate the subpattern as `{=\\n}` and should be documented as such

**Comment by eliocamp** [comment]
I think it looks good! 
The default could be any of those or even the actual default function what will be applied. This not only makes it clear that a function will be applied, but it also works to give the user some basic idea of how it works if they want to create a custom one.

**Comment by moodymudskipper** [comment]
@eliocamp this was all implemented among other things, there are a couple of breaking changes, so make sure to check the NEWS.md before updating.
